
name: problems

channels:
- pytorch
- conda-forge

dependencies:
- cython >= 3.0.8
#- onnx >= 1.16.2
- pip >= 24.3.1
- libopencv >= 4.10.0
#- py-opencv >= 4.9.0
- py-xgboost >= 2.0.3
- python >= 3.13.0
#- pytorch::pytorch >= 2.2.2
- pywavelets >= 1.5.0
- scipy >= 1.14.1
#- torchaudio >= 2.2.2
#- torchvision >= 0.17.2
- pip:
  - beartype >= 0.19.0
  - beautifulsoup4 >= 4.12.3
  - bitarray >= 3.0.0
  - black[jupyter] >= 24.10.0
  - dask >= 2024.12.1
  - datasets >= 3.2.0
  - evaluate >= 0.4.3
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 7.1.1
  - flask >= 3.0.2
  - flask-htmx >= 0.4.0
  - flask-restx >= 1.3.0
  - flask-sqlalchemy >= 3.1.1
  - geopandas >= 1.0.1
  - geopy >= 2.4.1
  - geoviews >= 1.14.0
  - glom >= 24.11.0
  - gpxpy >= 1.6.2
  - graphviz >= 0.20.3
  - gspread >= 6.1.4
  - gunicorn >= 23.0.0
  - gymnasium[classic-control] >= 1.0.0
  - html2text >= 2024.2.26
  - huggingface-hub >= 0.27.0
  - hypothesis >= 6.122.6
  - imbalanced-learn >= 0.13.0
  - ipyleaflet >= 0.19.2
  - isort >= 5.13.2
  - jupyterlab >= 4.3.4
  - kaggle >= 1.6.17
  - linetimer >= 0.1.5
  - lxml >= 5.3.0
  - markdownify >= 0.14.1
  - matplotlib >= 3.10.0
  - maturin >= 1.7.8
  - mechanicalsoup >= 1.3.0
  - memory-profiler >= 0.61.0
  - mplcursors >= 0.6
  - mypy >= 1.14.0
  - netifaces >= 0.11.0
  - numbers-parser >= 4.14.2
  - numpy >= 2.2.0
  - oauth2client >= 4.1.3
  - opencv-python-headless >= 4.10.0.84
  - openml >= 0.15.0
  - openpyxl >= 3.1.5
  - osmnx >= 2.0.0
  - palettable >= 3.3.3
  - pandas >= 2.2.3
  - pandas-stubs >= 2.2.3.241126
  - pillow >= 11.0.0
  - planegeometry >= 1.0.2
  - plotnine >= 0.14.4
  - polars >= 1.17.1
  - pre-commit >= 4.0.1
  - psutil >= 6.1.1
  - pyarrow >= 18.1.0
  - pyarrow-stubs >= 17.14
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.9.1
  - pydub >= 0.25.1
  - pygame >= 2.6.1
  - pylint >= 3.3.2
  - pynisher >= 1.0.10
  - pyo3-pack >= 0.6.1
  - pypandoc >= 1.14
  - pyright >= 1.1.391
  - pyspark >= 3.5.4
  - pytesseract >= 0.3.13
  - pytest >= 8.3.4
  - pytest-cov >= 5.0.0
  - python-levenshtein >= 0.26.1
  - python-docx >= 1.1.2
  - redis >= 5.2.1
  - reedsolo >= 1.7.0
  - requests-cache >= 1.2.1
  - requests-html >= 0.10.0
  - rouge-score >= 0.1.2
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.8.4
  - scikit-learn >= 1.6.0
  - scrapy >= 2.11.1
  - seaborn >= 0.13.2
  - selenium >= 4.27.1
  - sentencepiece >= 0.2.0
  - sqlacodegen-v2 >= 0.1.4
  - sqlalchemy >= 2.0.29
  - sqlalchemy_mate < 2.0.0.1
  - streamlit >= 1.41.1
  - streamlit-image-coordinates >= 0.2.0
  - swig >= 4.3.0
  - sympy >= 1.13.3
  - tabulate >= 0.9.0
  - typer >= 0.15.1
  - types-beautifulsoup4 >= 4.12.0.20241020
  - types-openpyxl >= 3.1.5.20241126
  - types-pillow >= 10.2.0.20240206
  - types-python-dateutil >= 2.9.0.20241206
  - types-redis >= 4.6.0.20241004
  - types-requests >= 2.32.0.20241016
  - types-seaborn >= 0.13.2.20241204
  - types-tabulate >= 0.9.0.20241207
  - types-tqdm >= 4.67.0.20241221
  - unidecode >= 1.3.8
  - uszipcode >= 1.0.1
  - uv >= 0.5.11
  - watchdog >= 6.0.0
  - xlsx2csv >= 0.8.4
  - yahoofinancials >= 1.20
  - yfinance[nospam] >= 0.2.51
#  - google-re2 >= 1.1.20240702
#  - gymnasium[box2d] >= 0.29.1
#  - networkit >= 11.0
#  - numba >= 0.60.0
#  - paddleocr >= 2.8.1
#  - pmdarima >= 2.0.4
#  - python-doctr >= 0.9.0
#  - spacy >= 3.7.6
#  - transformers >= 4.44.2
#  - tsdownsample >= 0.1.3
