
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.24
- dask >= 2022.8.0
- fasteners >= 0.17.3
- flake8 >= 5.0.4
- geopandas >= 0.11.1
- geopy >= 2.2.0
- glom >= 20.11.0
- imbalanced-learn >= 0.9.1
- ipyleaflet >= 0.17.0
- isort >= 5.10.1
- maturin >= 0.13.1
- netifaces >= 0.11.0
- networkit >= 10.0
- openml >= 0.12.2
- osmnx >= 1.2.2
- palettable >= 3.3.0
- pandas >= 1.4.3
- pandas-profiling >= 3.2.0
- pillow >= 9.0.1
- pip >= 22.2.2
- psutil >= 5.9.1
- py-opencv >= 4.6.0
- pyarrow >= 9.0.0
- pydeck >= 0.7.1
- pynisher >= 0.6.4
- pyo3-pack >= 0.3.6
- pytest >= 7.1.2
- python >= 3.9.7
- python-levenshtein >= 0.12.2
- ruamel.yaml >= 0.17.21
- scikit-learn >= 1.1.2
- scipy >= 1.9.0
- streamlit >= 1.11.1
- torchvision >= 0.10.1
- typer >= 0.6.1
- pip:
  - uszipcode >= 1.0.1
