
name: problems

channels:
- conda-forge

dependencies:
- pip >= 23.1
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.10.8, < 3.11
- pip:
  - black >= 23.3.0
  - cython >= 0.29.34
  - dask >= 2023.4.0
  - fasteners >= 0.18
  - flake8 >= 6.0.0
  - geopandas >= 0.12.2
  - geopy >= 2.3.0
  - glom >= 23.3.0
  - gpxpy >= 1.5.0
  - imbalanced-learn >= 0.10.1
  - ipyleaflet >= 0.17.2
  - isort >= 5.12.0
  - maturin >= 0.14.17
  - mypy >= 1.2.0
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - openml >= 0.13.1
  - osmnx >= 1.3.0
  - palettable >= 3.3.1
  - pandas >= 1.5.3
  - pandas-profiling >= 3.6.6
  - pillow >= 9.4
  - psutil >= 5.9.4
  - pyarrow >= 11.0.0
  - pydeck >= 0.8.0
  - pynisher >= 1.0.5
  - pyo3-pack >= 0.6.1
  - pytest >= 7.3.1
  - python-levenshtein >= 0.20.9
  - ruamel.yaml >= 0.17.21
  - scikit-learn >= 1.2.2
  - scipy >= 1.9.3
  - streamlit >= 1.21.0
  - tabulate >= 0.9.0
  - torchvision >= 0.15.1
  - typer >= 0.7.0
  - types-requests >= 2.28.11.17
  - uszipcode >= 1.0.1
