
name: problems

channels:
- conda-forge

dependencies:
- cython >= 3.0.8
- graph-tool >= 2.59
- numpy >= 1.26.4
- onnx >= 1.16.0
- pip >= 24.0
- py-opencv >= 4.9.0
- py-xgboost >= 2.0.3
- python >= 3.11.7
- pywavelets >= 1.5.0
- scipy >= 1.13.0
- pip:
  - beartype >= 0.18.5
  - beautifulsoup4 >= 4.12.3
  - bitarray >= 2.9.2
  - black[jupyter] >= 24.4.2
  - dask >= 2024.4.2
  - datasets >= 2.19.0
  - evaluate >= 0.4.2
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 7.0.0
  - flask >= 3.0.2
  - geopandas >= 0.14.4
  - geopy >= 2.4.1
  - geoviews >= 1.12.0
  - glom >= 23.5.0
  - gpxpy >= 1.6.2
  - graphviz >= 0.20.3
  - html2text >= 2024.2.26
  - huggingface_hub >= 0.20.2
  - hypothesis >= 6.100.2
  - imbalanced-learn >= 0.12.2
  - ipyleaflet >= 0.19.0
  - isort >= 5.13.2
  - jupyterlab >= 4.1.8
  - kaggle >= 1.6.12
  - lxml >= 5.2.1
  - markdownify >= 0.12.1
  - matplotlib >= 3.8.4
  - maturin >= 1.5.1
  - memory-profiler >= 0.61.0
  - mypy >= 1.10.0
  - netifaces >= 0.11.0
  - networkit >= 11.0
  - numba >= 0.59.1
  - numbers_parser >= 3.11.0
  - openml >= 0.14.2
  - openpyxl >= 3.1.2
  - osmnx >= 1.9.3
  - palettable >= 3.3.3
  - pandas >= 2.2.2
  - pandas-stubs >= 2.2.1.240316
  - pillow >= 10.3.0
  - plotnine >= 0.13.5
  - polars >= 0.20.23
  - psutil >= 5.9.8
  - pyarrow >= 16.0.0
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.9.0
  - pydub >= 0.25.1
  - pygame >= 2.5.2
  - pylint >= 3.1.0
  - pynisher >= 1.0.10
  - pyo3-pack >= 0.6.1
  - pyright >= 1.1.361
  - pyspark >= 3.5.1
  - pytesseract >= 0.3.10
  - pytest >= 8.2.0
  - pytest-cov >= 5.0.0
  - python-Levenshtein >= 0.25.1
  - redis >= 5.0.4
  - requests_cache >= 1.1.1
  - requests_html >= 0.10.0
  - rouge_score >= 0.1.2
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.4.2
  - scikit-learn >= 1.4.2
  - seaborn >= 0.13.2
  - sentencepiece >= 0.2.0
  - spacy >= 3.7.4
  - sqlalchemy >= 2.0.29
  - streamlit >= 1.33.0
  - streamlit-image-coordinates >= 0.1.6
  - sympy >= 1.12
  - tabulate >= 0.9.0
  - transformers >= 4.40.1
  - tsdownsample >= 0.1.3
  - typer >= 0.9.4
  - types-beautifulsoup4 >= 4.12.0.20240229
  - types-openpyxl >= 3.1.0.20240428
  - types-pillow >= 10.2.0.20240206
  - types-python-dateutil >= 2.9.0.20240316
  - types-redis >= 4.6.0.20240425
  - types-requests >= 2.31.0.20240406
  - types-tqdm >= 4.66.0.20240417
  - unidecode >= 1.3.8
  - uszipcode >= 1.0.1
  - watchdog >= 4.0.0
  - xlsx2csv >= 0.8.2
