
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.24
- dask >= 2022.4.1
- fasteners >= 0.17.3
- flake8 >= 4.0.1
- geopandas >= 0.10.2
- geopy >= 2.2.0
- glom >= 20.11.0
#- hpbandster >= 0.7.4  # better to use https://github.com/automl/SMAC3
- imbalanced-learn >= 0.8.1
- isort >= 5.10.1
- netifaces >= 0.10.9
- networkit >= 9.1.1
- openml >= 0.12.2
- palettable >= 3.3.0
- pandas >= 1.4.2
- pandas-profiling >= 3.1.0
- pillow >= 9.0.1
- pip >= 22.0.4
- psutil >= 5.9.0
- py-opencv >= 4.5.3
- pyarrow >= 7.0.0
- pydeck >= 0.7.1
- pynisher >= 0.6.4
- pytest >= 7.1.1
- python >= 3.9.7
- ruamel.yaml >= 0.17.21
- scikit-learn >= 0.24.2
- scipy >= 1.8.0
- streamlit >= 1.8.1
- torchvision >= 0.10.1
- typer >= 0.4.1
#- pip:
#  - autopytorch >= 0.0.2  # This wants catboost >= 1.0.4 & pyrfr >= 0.8.2
