
name: problems

channels:
- conda-forge

dependencies:
- flake8 >= 4.0.1
- isort >= 5.9.3
- pandas >= 1.3.3
- pip >= 21.3
- pyarrow >= 5.0.0
- python >= 3.9.7
- pytorch >= 1.9.1
- ruamel.yaml >= 0.17.16
- scikit-learn >= 0.20.0  # or 1.0
- pip:
  - autopytorch >= 0.0.2
