
name: problems

channels:
- conda-forge

dependencies:
- flake8 >= 4.0.1
- geopandas >= 0.10.1
- geopy >= 2.2.0
- isort >= 5.9.3
- palettable >= 3.3.0
- pandas >= 1.2.5
- pandas-profiling >= 3.1.0
- pip >= 21.3
- pyarrow >= 5.0.0
- pydeck >= 0.7.0
- python >= 3.9.7
- pytorch >= 1.9.1
- ruamel.yaml >= 0.17.16
- scikit-learn >= 1.0
- streamlit >= 1.0.0
- pip:
  - autopytorch >= 0.0.2
