
name: problems

channels:
- pytorch
- conda-forge

dependencies:
- cython >= 3.0.8
- numpy >= 2.0.2
#- onnx >= 1.16.2
- pip >= 24.2
- libopencv >= 4.10.0
#- py-opencv >= 4.9.0
- py-xgboost >= 2.0.3
- python >= 3.13.0
#- pytorch::pytorch >= 2.2.2
- pywavelets >= 1.5.0
- scipy >= 1.14.1
#- torchaudio >= 2.2.2
#- torchvision >= 0.17.2
- pip:
  - beartype >= 0.19.0
  - beautifulsoup4 >= 4.12.3
  - bitarray >= 3.0.0
  - black[jupyter] >= 24.10.0
  - dask >= 2024.10.0
  - datasets >= 3.0.1
  - evaluate >= 0.4.3
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 7.1.1
  - flask >= 3.0.2
  - flask-htmx >= 0.4.0
  - flask-restx >= 1.3.0
  - flask-sqlalchemy >= 3.1.1
  - geopandas >= 1.0.1
  - geopy >= 2.4.1
  - geoviews >= 1.13.0
  - glom >= 23.5.0
  - gpxpy >= 1.6.2
  - graphviz >= 0.20.3
  - gspread >= 6.1.4
  - gunicorn >= 23.0.0
  - html2text >= 2024.2.26
  - huggingface-hub >= 0.26.1
  - hypothesis >= 6.115.3
  - imbalanced-learn >= 0.12.4
  - ipyleaflet >= 0.19.2
  - isort >= 5.13.2
  - jupyterlab >= 4.2.5
  - kaggle >= 1.6.17
  - linetimer >= 0.1.5
  - lxml >= 5.3.0
  - markdownify >= 0.13.1
  - matplotlib >= 3.9.2
  - maturin >= 1.7.4
  - mechanicalsoup >= 1.3.0
  - memory-profiler >= 0.61.0
  - mplcursors >= 0.5.3
  - mypy >= 1.12.1
  - netifaces >= 0.11.0
  - numbers-parser >= 4.14.1
  - oauth2client >= 4.1.3
  - opencv-python >= 0
  - opencv-python-headless >= 0
  - openml >= 0.15.0
  - openpyxl >= 3.1.5
  - osmnx >= 1.9.3
  - palettable >= 3.3.3
  - pandas >= 2.2.3
  - pandas-stubs >= 2.2.3.241009
  - pillow >= 10.4.0
  - planegeometry >= 1.0.2
  - plotnine >= 0.13.6
  - polars >= 1.10.0
  - pre-commit >= 4.0.1
  - psutil >= 6.1.0
  - pyarrow >= 17.0.0
  - pyarrow-stubs >= 17.12
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.9.1
  - pydub >= 0.25.1
  - pygame >= 2.6.1
  - pylint >= 3.3.1
  - pynisher >= 1.0.10
  - pyo3-pack >= 0.6.1
  - pypandoc >= 1.14
  - pyright >= 1.1.389
  - pyspark >= 3.5.3
  - pytesseract >= 0.3.13
  - pytest >= 8.3.3
  - pytest-cov >= 5.0.0
  - python-Levenshtein >= 0.26.0
  - python-docx >= 1.1.2
  - redis >= 5.1.1
  - reedsolo >= 1.7.0
  - requests-cache >= 1.2.1
  - requests-html >= 0.10.0
  - rouge-score >= 0.1.2
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.7.0
  - scikit-learn >= 1.5.2
  - scrapy >= 2.11.1
  - seaborn >= 0.13.2
  - selenium >= 4.25.0
  - sentencepiece >= 0.2.0
  - sqlacodegen-v2 >= 0.1.4
  - sqlalchemy >= 2.0.29
  - sqlalchemy_mate < 2.0.0.1
  - streamlit >= 1.39.0
  - streamlit-image-coordinates >= 0.1.9
  - swig >= 4.2.1
  - sympy >= 1.13.3
  - tabulate >= 0.9.0
  - typer >= 0.12.5
  - types-beautifulsoup4 >= 4.12.0.20241020
  - types-openpyxl >= 3.1.5.20241020
  - types-pillow >= 10.2.0.20240206
  - types-python-dateutil >= 2.9.0.20241003
  - types-redis >= 4.6.0.20241004
  - types-requests >= 2.32.0.20241016
  - types-seaborn >= 0.13.2.20241003
  - types-tabulate >= 0.9.0.20240106
  - types-tqdm >= 4.66.0.20240417
  - unidecode >= 1.3.8
  - uszipcode >= 1.0.1
  - uv >= 0.4.25
  - watchdog >= 5.0.3
  - xlsx2csv >= 0.8.3
  - yahoofinancials >= 1.20
  - yfinance[nospam] >= 0.2.46
#  - google-re2 >= 1.1.20240702
#  - gymnasium[box2d] >= 0.29.1
#  - networkit >= 11.0
#  - numba >= 0.60.0
#  - paddleocr >= 2.8.1
#  - pmdarima >= 2.0.4
#  - python-doctr >= 0.9.0
#  - spacy >= 3.7.6
#  - transformers >= 4.44.2
#  - tsdownsample >= 0.1.3
