
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.34
- matplotlib >= 3.7.2
- numpy == 1.24.4
- pandas >= 2.0.3
- pillow == 9.5.0
- pip >= 23.2
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.11.4
- python-levenshtein >= 0.20.9
- pywavelets >= 1.4.1
- scipy >= 1.11.1
- torchvision >= 0.9.1
- pip:
  - beautifulsoup4 >= 4.12.2
  - bitarray >= 2.7.6
  - black >= 23.3.0
  - dask >= 2023.6.1
  - eyed3 >= 0.9.7
  - fasteners >= 0.18
  - flake8 >= 6.0.0
  - geopandas >= 0.13.2
  - geopy >= 2.3.0
  - glom >= 23.3.0
  - gpxpy >= 1.5.0
  - hypothesis >= 6.80.0
  - imbalanced-learn >= 0.10.1
  - ipyleaflet >= 0.17.3
  - isort >= 5.12.0
  - lxml >= 4.9.2
  - markdownify >= 0.11.6
  - maturin >= 1.1.0
  - memory-profiler >= 0.61.0
  - mypy >= 1.4.1
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - numba >= 0.57.1
  - numbers_parser >= 3.11.0
  - openml >= 0.13.1
  - openpyxl >= 3.1.2
  - osmnx >= 1.5.0
  - palettable >= 3.3.3
  - pandas-profiling >= 3.2.0
  - polars >= 0.18.4
  - psutil >= 5.9.5
  - pyarrow >= 12.0.1
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.8.0
  - pydub >= 0.25.1
  - pynisher >= 1.0.5
  - pyo3-pack >= 0.6.1
  - pytest >= 7.4.0
  - pytest-cov >= 4.1.0
  - roman >= 3.3
  - ruamel.yaml >= 0.17.32
  - ruff >= 0.0.275
  - scikit-learn >= 1.2.2
  - spacy >= 3.5.4
  - sqlalchemy >= 1.4.47, < 2
  - streamlit >= 1.24.0
  - tabulate >= 0.9.0
  - typer >= 0.9.0
  - types-requests >= 2.31.0.1
  - uszipcode >= 1.0.1
  - watchdog >= 3.0.0
  - xlsx2csv >= 0.0.1
