
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.34
- pip >= 23.2.1
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.11.4
- torchvision >= 0.9.1
- pip:
  - beautifulsoup4 >= 4.12.2
  - bitarray >= 2.8.1
  - black[jupyter] >= 23.9.0
  - dask >= 2023.9.1
  - datasets >= 2.14.5
  - evaluate >= 0.4.0
#  - eyed3 >= 0.9.7  # coverage[toml]<6.0.0,>=5.3.1 (from eyed3>=0.9.7, for audio ID3 tags)
  - fasteners >= 0.18
  - flake8 >= 6.1.0
  - flask >= 2.3.2
  - geopandas >= 0.13.2
  - geopy >= 2.4.0
  - glom >= 23.3.0
  - gpxpy >= 1.5.0
  - huggingface_hub >= 0.16.4
  - hypothesis >= 6.84.2
  - imbalanced-learn >= 0.11.0
  - ipyleaflet >= 0.17.3
  - isort >= 5.12.0
  - lxml >= 4.9.3
  - markdownify >= 0.11.6
  - matplotlib >= 3.7.2
  - maturin >= 1.2.3
  - memory-profiler >= 0.61.0
  - mypy >= 1.5.1
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - html2text >= 2020.1.16
  - numba >= 0.57.1
  - numbers_parser >= 3.11.0
  - numpy >= 1.23.5
  - onnx >= 1.14.1
  - openml >= 0.14.1
  - openpyxl >= 3.1.2
  - osmnx >= 1.6.0
  - palettable >= 3.3.3
  - pandas >= 2.0.3
  - pillow >= 9.5.0
  - polars >= 0.19.2
  - psutil >= 5.9.5
  - pyarrow >= 13.0.0
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.8.0
  - pydub >= 0.25.1
  - pygame >= 2.5.1
  - pylint >= 2.17.5
  - pynisher >= 1.0.9
  - pyo3-pack >= 0.6.1
  - pyspark >= 3.4.1
  - pytest >= 7.4.2
  - pytest-cov >= 4.1.0
  - python-Levenshtein >= 0.21.1
  - pywavelets >= 1.4.1
  - roman >= 3.3
  - rouge_score >= 0.1.2
  - ruamel.yaml >= 0.17.32
  - ruff >= 0.0.287
  - scikit-learn >= 1.3.0
  - scipy >= 1.11.2
  - sentencepiece >= 0.1.99
  - spacy >= 3.6.1
  - sqlalchemy >= 1.4.47, < 2
  - streamlit >= 1.26.0
  - streamlit-image-coordinates >= 0.1.6
  - tabulate >= 0.9.0
  - transformers >= 4.33.1
  - typer >= 0.9.0
  - types-requests >= 2.31.0.2
  - unidecode >= 1.3.6
  - uszipcode >= 1.0.1
  - watchdog >= 3.0.0
  - xlsx2csv >= 0.8.1
  - ydata-profiling >= 4.5.1
