
name: problems

channels:
- conda-forge

dependencies:
- black >= 22.12.0
- cython >= 0.29.24
- dask >= 2022.12.1
- fasteners >= 0.17.3
- flake8 >= 6.0.0
- geopandas >= 0.12.2
- geopy >= 2.3.0
- glom >= 20.11.0
- gpxpy >= 1.5.0
- imbalanced-learn >= 0.10.1
- ipyleaflet >= 0.17.2
- isort >= 5.11.4
- maturin >= 0.14.9
- mypy >= 0.991
- netifaces >= 0.11.0
- networkit >= 10.0
- openml >= 0.12.2
- osmnx >= 1.3.0
- palettable >= 3.3.0
- pandas >= 1.5.2
- pandas-profiling >= 3.2.0
- pillow >= 9.0.1
- pip >= 22.3.1
- polars >= 0.16.4
- psutil >= 5.9.4
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- pyarrow >= 9.0.0
- pydeck >= 0.7.1
- pynisher >= 1.0.0
- pyo3-pack >= 0.3.6
- pytest >= 7.2.0
- pytest-cov >= 4.0.0
- python >= 3.10.8, < 3.11
- python-levenshtein >= 0.12.2
- ruamel.yaml >= 0.17.21
- scikit-learn >= 1.2.0
- scipy >= 1.9.3
- streamlit >= 1.16.0
- tabulate >= 0.9.0
- torchvision >= 0.10.1
- typer >= 0.7.0
- types-requests >= 2.28.11.7
- types-tqdm >= 4.64.7.12
- pip:
  - uszipcode >= 1.0.1
