
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.34
- matplotlib == 3.6.3
- numpy == 1.23.5
- pandas >= 1.5.3, < 2
- pip >= 23.1.2
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.10.10, < 3.11
- python-levenshtein >= 0.20.9
- pywavelets >= 1.4.1
- scipy == 1.9.3
- torchvision >= 0.9.1
- pip:
  - beautifulsoup4 >= 4.12.2
  - bitarray >= 2.7.4
  - black >= 23.3.0
  - dask >= 2023.5.1
  - fasteners >= 0.18
  - flake8 >= 6.0.0
  - geopandas >= 0.13.0
  - geopy >= 2.3.0
  - glom >= 23.3.0
  - gpxpy >= 1.5.0
  - hypothesis >= 6.75.6
  - imbalanced-learn >= 0.10.1
  - ipyleaflet >= 0.17.2
  - isort >= 5.12.0
  - lxml >= 4.9.2
  - markdownify >= 0.11.6
  - maturin >= 1.0.1
  - memory-profiler >= 0.61.0
  - mypy >= 1.3.0
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - numba >= 0.57.0
  - openml >= 0.13.1
  - osmnx >= 1.3.1
  - palettable >= 3.3.3
  - pandas-profiling >= 3.6.6
  - pillow >= 9.4
  - polars >= 0.18.0
  - psutil >= 5.9.5
  - pyarrow >= 12.0.0
  - pydeck >= 0.8.0
  - pynisher >= 1.0.5
  - pyo3-pack >= 0.6.1
  - pytest >= 7.3.1
  - pytest-cov >= 4.1.0
  - roman >= 4.1
  - ruamel.yaml >= 0.17.28
  - ruff >= 0.0.270
  - scikit-learn >= 1.2.2
  - spacy >= 3.5.3
  - sqlalchemy >= 1.4.47, < 2
  - streamlit >= 1.22.0
  - tabulate >= 0.9.0
  - typer >= 0.9.0
  - types-requests >= 2.31.0.1
  - uszipcode >= 1.0.1
