
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.34
- pip >= 23.3.1
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.11.4
- torchvision >= 0.9.1
- pip:
  - beartype >= 0.16.4
  - beautifulsoup4 >= 4.12.2
  - bitarray >= 2.8.2
  - black[jupyter] >= 23.10.1
  - dask >= 2023.10.1
  - datasets >= 2.14.6
  - evaluate >= 0.4.1
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 5.0.4  # down from 6.1.0
  - flask >= 2.3.2
  - geopandas >= 0.14.0
  - geopy >= 2.4.0
  - glom >= 23.3.0
  - gpxpy >= 1.6.1
  - html2text >= 2020.1.16
  - huggingface_hub >= 0.16.4
  - hypothesis >= 6.88.1
  - imbalanced-learn >= 0.11.0
  - ipyleaflet >= 0.17.4
  - isort >= 5.12.0
  - lxml >= 4.9.3
  - markdownify >= 0.11.6
  - matplotlib >= 3.7.3
  - maturin >= 1.3.1
  - memory-profiler >= 0.61.0
  - mypy >= 1.6.1
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - numba >= 0.58.1
  - numbers_parser >= 3.11.0
  - numpy >= 1.24.4, < 1.25  # numba works with 1.24
  - onnx >= 1.15.0
  - openml >= 0.14.1
  - openpyxl >= 3.1.2
  - osmnx >= 1.7.1
  - palettable >= 3.3.3
  - pandas >= 2.0.3
  - pillow >= 9.5.0
  - polars >= 0.19.12
  - psutil >= 5.9.6
  - pyarrow >= 14.0.0
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.8.0
  - pydub >= 0.25.1
  - pygame >= 2.5.2
  - pylint >= 2.17.7
  - pynisher >= 1.0.9
  - pyo3-pack >= 0.6.1
  - pyspark >= 3.5.0
  - pytest >= 7.4.3
  - pytest-cov >= 4.1.0
  - python-Levenshtein >= 0.23.0
  - pywavelets >= 1.4.1
  - roman >= 3.3
  - rouge_score >= 0.1.2
  - ruamel.yaml >= 0.18.4
  - ruff >= 0.1.3
  - scikit-learn >= 1.3.2
  - scipy >= 1.11.3
  - sentencepiece >= 0.1.99
  - spacy >= 3.7.2
  - sqlalchemy >= 1.4.47, < 2
  - streamlit >= 1.28.0
  - streamlit-image-coordinates >= 0.1.6
  - tabulate >= 0.9.0
  - transformers >= 4.34.1
  - typer >= 0.9.0
  - types-requests >= 2.31.0.10
  - unidecode >= 1.3.6
  - uszipcode >= 1.0.1
  - watchdog >= 3.0.0
  - xlsx2csv >= 0.8.1
  - ydata-profiling >= 4.6.1
