
name: problems

channels:
- conda-forge

dependencies:
- cython >= 0.29.34
- pip >= 23.3.2
- py-opencv >= 4.6.0
- py-xgboost >= 1.7.1
- python >= 3.11.4
- torchvision >= 0.16.1
- pip:
  - beartype >= 0.16.4
  - beautifulsoup4 >= 4.12.2
  - bitarray >= 2.9.2
  - black[jupyter] >= 23.12.1
  - dask >= 2023.12.1
  - datasets >= 2.16.1
  - evaluate >= 0.4.1
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 6.1.0
  - flask >= 2.3.2
  - geopandas >= 0.14.1
  - geopy >= 2.4.1
  - geoviews >= 1.11.0
  - glom >= 23.5.0
  - gpxpy >= 1.6.2
  - html2text >= 2020.1.16
  - huggingface_hub >= 0.16.4
  - hypothesis >= 6.92.2
  - imbalanced-learn >= 0.11.0
  - ipyleaflet >= 0.18.1
  - isort >= 5.13.2
  - lxml >= 5.0.0
  - markdownify >= 0.11.6
  - matplotlib >= 3.8.2
  - maturin >= 1.4.0
  - memory-profiler >= 0.61.0
  - mypy >= 1.8.0
  - netifaces >= 0.11.0
  - networkit >= 10.1
  - numba >= 0.58.1
  - numbers_parser >= 3.11.0
  - numpy >= 1.25.2
  - onnx >= 1.15.0
  - openml >= 0.14.1
  - openpyxl >= 3.1.2
  - osmnx >= 1.8.1
  - palettable >= 3.3.3
  - pandas >= 2.1.4
  - pandas-stubs >= 2.1.4.231227
  - pillow >= 10.2.0
  - plotnine >= 0.12.4
  - polars >= 0.20.3
  - psutil >= 5.9.7
  - pyarrow >= 14.0.2
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.8.0
  - pydub >= 0.25.1
  - pygame >= 2.5.2
  - pylint >= 3.0.3
  - pynisher >= 1.0.10
  - pyo3-pack >= 0.6.1
  - pyspark >= 3.5.0
  - pytest >= 7.4.4
  - pytest-cov >= 4.1.0
  - python-Levenshtein >= 0.23.0
  - pywavelets >= 1.4.1
  - requests_cache >= 1.1.1
  - roman >= 3.3
  - rouge_score >= 0.1.2
  - ruamel.yaml >= 0.18.5
  - ruff >= 0.1.11
  - scikit-learn >= 1.3.2
  - scipy >= 1.11.3
  - sentencepiece >= 0.1.99
  - spacy >= 3.7.2
  - sqlalchemy >= 1.4.47, < 2
  - streamlit >= 1.29.0
  - streamlit-image-coordinates >= 0.1.6
  - tabulate >= 0.9.0
  - transformers >= 4.36.2
  - typer >= 0.9.0
  - types-requests >= 2.31.0.20231231
  - types_beautifulsoup4 >= 4.12.0.20240106
  - unidecode >= 1.3.6
  - uszipcode >= 1.0.1
  - watchdog >= 3.0.0
  - xlsx2csv >= 0.8.2
  - ydata-profiling >= 4.6.3
