
name: problems

channels:
- pytorch
- conda-forge

dependencies:
- cython >= 3.0.8
- graph-tool >= 2.59
- numpy >= 1.26.4
- onnx >= 1.16.1
- pip >= 24.1.2
- py-opencv >= 4.9.0
- py-xgboost >= 2.0.3
- python >= 3.12.3
- pytorch::pytorch >= 2.2.2
- pywavelets >= 1.5.0
- scipy >= 1.14.0
- torchaudio >= 2.2.2
- torchvision >= 0.17.2
- pip:
  - beartype >= 0.18.5
  - beautifulsoup4 >= 4.12.3
  - bitarray >= 2.9.2
  - black[jupyter] >= 24.4.2
  - dask >= 2024.7.1
  - datasets >= 2.20.0
  - evaluate >= 0.4.2
  - eyed3 >= 0.9.7
  - fasteners >= 0.19
  - flake8 >= 7.1.0
  - flask >= 3.0.2
  - flask-htmx >= 0.3.2
  - flask-restx >= 1.3.0
  - flask-sqlalchemy >= 3.1.1
  - geopandas >= 1.0.1
  - geopy >= 2.4.1
  - geoviews >= 1.12.0
  - glom >= 23.5.0
  - gpxpy >= 1.6.2
  - graphviz >= 0.20.3
  - gspread >= 6.1.2
  - gunicorn >= 22.0.0
  - gymnasium[box2d] >= 0.29.1
  - html2text >= 2024.2.26
  - huggingface-hub >= 0.24.5
  - hypothesis >= 6.108.5
  - imbalanced-learn >= 0.12.3
  - ipyleaflet >= 0.19.2
  - isort >= 5.13.2
  - jupyterlab >= 4.2.4
  - kaggle >= 1.6.17
  - linetimer >= 0.1.5
  - lxml >= 5.2.2
  - markdownify >= 0.13.1
  - matplotlib >= 3.9.1
  - maturin >= 1.7.0
  - mechanicalsoup >= 1.3.0
  - memory-profiler >= 0.61.0
  - mplcursors >= 0.5.3
  - mypy >= 1.11.1
  - netifaces >= 0.11.0
  - networkit >= 11.0
  - numba >= 0.60.0
  - numbers-parser >= 4.12.2
  - oauth2client >= 4.1.3
  - openml >= 0.14.2
  - openpyxl >= 3.1.5
  - osmnx >= 1.9.3
  - palettable >= 3.3.3
  - pandas >= 2.2.2
  - pandas-stubs >= 2.2.2.240603
  - pillow >= 10.4.0
  - plotnine >= 0.13.6
  - pmdarima >= 2.0.4
  - polars >= 1.3.0
  - psutil >= 6.0.0
  - pyarrow >= 17.0.0
  - pyaudioanalysis >= 0.3.14
  - pydeck >= 0.9.1
  - pydub >= 0.25.1
  - pygame >= 2.6.0
  - pylint >= 3.2.6
  - pynisher >= 1.0.10
  - pyo3-pack >= 0.6.1
  - pyright >= 1.1.374
  - pyspark >= 3.5.1
  - pytesseract >= 0.3.10
  - pytest >= 8.3.2
  - pytest-cov >= 5.0.0
  - python-Levenshtein >= 0.25.1
  - python-doctr >= 0.9.0
  - redis >= 5.0.8
  - reedsolo >= 1.7.0
  - requests-cache >= 1.2.1
  - requests-html >= 0.10.0
  - rouge-score >= 0.1.2
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.5.5
  - scikit-learn >= 1.5.1
  - scrapy >= 2.11.1
  - seaborn >= 0.13.2
  - selenium >= 4.23.1
  - sentencepiece >= 0.2.0
  - spacy >= 3.7.5
  - sqlacodegen-v2 >= 0.1.4
  - sqlalchemy >= 2.0.29
  - streamlit >= 1.37.0
  - streamlit-image-coordinates >= 0.1.9
  - swig >= 4.2.1
  - sympy >= 1.13.1
  - tabulate >= 0.9.0
  - transformers >= 4.43.3
  - tsdownsample >= 0.1.3
  - typer >= 0.12.3
  - types-beautifulsoup4 >= 4.12.0.20240511
  - types-openpyxl >= 3.1.5.20240719
  - types-pillow >= 10.2.0.20240206
  - types-python-dateutil >= 2.9.0.20240316
  - types-redis >= 4.6.0.20240726
  - types-requests >= 2.32.0.20240712
  - types-tabulate >= 0.9.0.20240106
  - types-tqdm >= 4.66.0.20240417
  - unidecode >= 1.3.8
  - uszipcode >= 1.0.1
  - watchdog >= 4.0.1
  - xlsx2csv >= 0.8.3
  - yahoofinancials >= 1.20
  - yfinance[nospam] >= 0.2.41
