
[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "def main\\(",
]

[tool.pylint]
[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
good-names = """
    a, b, c, d, f, g, h, i, j, k, m, n, p, q, r, s, t, u, v, w, x, y, z,
    ax, df, hi, lo, pt, t0, t1, t2, ts, xs,
    ul, lr,
"""
disable = """
    C0114, missing-module-docstring,
    C0115, missing-class-docstring,
    C0116, missing-function-docstring,
    W1203, logging-fstring-interpolation,
    W3101, missing-timeout,
"""

[tool.pyright]
reportMissingTypeStubs = false

[tool.ruff]
line-length = 120
