
# conda env update -f geo/wed/ds/caret-environment.yml

name: caret

channels:
- conda-forge

dependencies:
- pip >= 24.0
- python >= 3.11.8, < 3.12
- pip:
  - black[jupyter] >= 24.3.0
  - hypothesis >= 6.99.13
  - isort >= 5.13.2
  - jupyterlab >= 4.1.5
  - pandas >= 2.1.4
  - pandas-stubs >= 2.1.4
  - pycaret >= 3.3.0
  - pytest-cov >= 4.1.0
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.3.4
  - seaborn >= 0.12.2
  - tsdownsample >= 0.1.2
  - ydata_profiling >= 4.7.0
