
# conda env update -f geo/wed/ds/caret-environment.yml

name: caret

channels:
- conda-forge

dependencies:
- pip >= 24.0
- python >= 3.9, < 3.12
- pip:
  - black[jupyter] >= 24.3.0
  - hypothesis >= 6.99.11
  - isort >= 5.13.2
  - jupyterlab >= 4.1.5
  - pandas >= 1.5.0
  - pandas-stubs >= 1.5.0
  - pycaret >= 3.0.0
  - pytest-cov >= 4.1.0
  - ruamel.yaml >= 0.18.6
  - ruff >= 0.3.3
  - seaborn >= 0.13.2
  - tsdownsample >= 0.1.3
  - ydata_profiling >= 0.0.1
