[package]
name = "rust_lib"
version = "0.1.0"
authors = ["John Hanley <jhanley708-git@s6.sector6.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
